#!/usr/bin/env ruby
require_relative 'run.rb'

def main
  no_changes_in_protos!
  run!(%w[_support/install-protoc])
  run!(%w[_support/generate-from-proto])
  no_changes_in_protos!
  puts 'OK! The gRPC / Protobuf clients are up-to-date'
end

def no_changes_in_protos!
  changes = capture!(%w[git status --porcelain -- protos]).chomp
  if changes.lines.any?
    puts changes
    abort 'error: detected changes in /protos'
  end
end

main
