#!/bin/sh
set -e

if [ $# -ne 1 ] ; then
  echo "Usage: $0 [ -n | -f ]"
  echo
  echo "$0 runs 'gofmt -s' on all non-vendored .go files in this project."
  echo "  -n  List files that would be changed"
  echo "  -f  Apply changes"
  exit 1
fi

gofmt='gofmt -s -l'
case "x$1" in
x-n)
  # Command is already as it should be.
  ;;
x-f)
  gofmt="${gofmt} -w"
  ;;
*)
  echo "Invalid argument: $1"
  exit 1
  ;;
esac
  
${gofmt} $(find . -name '*.go' -not -path './vendor/*' -not -path './_*')
