#!/bin/sh

set -eu
IFS=$'\n\t'
BUILD_DIR="$( cd "$( dirname "$0" )" && cd .. && pwd )"

cd "${BUILD_DIR}"

# Iterate through all the lintable directories and run go lint 
go list  -f '{{.Dir}}' ./... | \
        grep -vE "^${BUILD_DIR}/vendor|protos" | \
        sed -e "s#^${BUILD_DIR}/##" | \
        while read dir; do
        
    # Lint the directory containing lintable go sources
    golint -set_exit_status "${dir}"
done
