require 'yaml'

NO_CHANGELOG_LABELS = %w[backstage documentation test].freeze
SEE_DOC = "See [the documentation](https://gitlab.com/gitlab-org/gitaly/blob/master/CONTRIBUTING.md#changelog)".freeze
CREATE_CHANGELOG_MESSAGE = <<~MSG.freeze
You can create one with:

```
_support/changelog -m %<mr_iid>s "%<mr_title>s"
```

If your merge request doesn't warrant a CHANGELOG entry,
consider adding any of the %<labels>s labels.
MSG

def check_changelog(path)
  yaml = YAML.load_file(path)

  fail "`title` should be set, in #{gitlab.html_link(path)}! #{SEE_DOC}" if yaml["title"].nil?
  fail "`type` should be set, in #{gitlab.html_link(path)}! #{SEE_DOC}" if yaml["type"].nil?

  if yaml["merge_request"].nil?
    message "Consider setting `merge_request` to #{gitlab.mr_json["iid"]} in #{gitlab.html_link(path)}. #{SEE_DOC}"
  elsif yaml["merge_request"] != gitlab.mr_json["iid"]
    fail "Merge request ID was not set to #{gitlab.mr_json["iid"]}! #{SEE_DOC}"
  end

  if yaml["type"].nil?
    fail "No type was set in the changelog"
  end
rescue Psych::SyntaxError, Psych::DisallowedClass, Psych::BadAlias
  # YAML could not be parsed, fail the build.
  fail "#{gitlab.html_link(path)} isn't valid YAML! #{SEE_DOC}"
rescue StandardError => e
  warn "There was a problem trying to check the Changelog. Exception: #{e.name} - #{e.message}"
end

def presented_no_changelog_labels
  NO_CHANGELOG_LABELS.map { |label| "~#{label}" }.join(', ')
end

changelog_needed = (gitlab.mr_labels & NO_CHANGELOG_LABELS).empty?
changelog_found = git.added_files.find { |path| path =~ %r{\Achangelogs/unreleased/} }

mr_title = gitlab.mr_json["title"].gsub(/^WIP: */, '')

if git.modified_files.include?("CHANGELOG.md")
  fail "**CHANGELOG.md was edited.** Please remove the additions and create a CHANGELOG entry.\n\n" +
    format(CREATE_CHANGELOG_MESSAGE, mr_iid: gitlab.mr_json["iid"], mr_title: mr_title, labels: presented_no_changelog_labels)
end

if changelog_needed
  if changelog_found
    check_changelog(changelog_found)
  else
    warn "**[CHANGELOG missing](https://docs.gitlab.com/ce/development/changelog.html).**\n\n" +
      format(CREATE_CHANGELOG_MESSAGE, mr_iid: gitlab.mr_json["iid"], mr_title: mr_title, labels: presented_no_changelog_labels)
  end
end

# vim: ft=ruby
