// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go/internal/linter/testdata/valid.proto

package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import gitalypb "gitlab.com/gitlab-org/gitaly/proto/go/gitalypb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ValidRequest struct {
	Destination          *gitalypb.Repository `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ValidRequest) Reset()         { *m = ValidRequest{} }
func (m *ValidRequest) String() string { return proto.CompactTextString(m) }
func (*ValidRequest) ProtoMessage()    {}
func (*ValidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_valid_28fe26eda283975a, []int{0}
}
func (m *ValidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidRequest.Unmarshal(m, b)
}
func (m *ValidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidRequest.Marshal(b, m, deterministic)
}
func (dst *ValidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidRequest.Merge(dst, src)
}
func (m *ValidRequest) XXX_Size() int {
	return xxx_messageInfo_ValidRequest.Size(m)
}
func (m *ValidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidRequest proto.InternalMessageInfo

func (m *ValidRequest) GetDestination() *gitalypb.Repository {
	if m != nil {
		return m.Destination
	}
	return nil
}

type ValidResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidResponse) Reset()         { *m = ValidResponse{} }
func (m *ValidResponse) String() string { return proto.CompactTextString(m) }
func (*ValidResponse) ProtoMessage()    {}
func (*ValidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_valid_28fe26eda283975a, []int{1}
}
func (m *ValidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidResponse.Unmarshal(m, b)
}
func (m *ValidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidResponse.Marshal(b, m, deterministic)
}
func (dst *ValidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidResponse.Merge(dst, src)
}
func (m *ValidResponse) XXX_Size() int {
	return xxx_messageInfo_ValidResponse.Size(m)
}
func (m *ValidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidResponse proto.InternalMessageInfo

type ValidNestedRequest struct {
	InnerMessage         *ValidRequest `protobuf:"bytes,1,opt,name=inner_message,json=innerMessage,proto3" json:"inner_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ValidNestedRequest) Reset()         { *m = ValidNestedRequest{} }
func (m *ValidNestedRequest) String() string { return proto.CompactTextString(m) }
func (*ValidNestedRequest) ProtoMessage()    {}
func (*ValidNestedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_valid_28fe26eda283975a, []int{2}
}
func (m *ValidNestedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidNestedRequest.Unmarshal(m, b)
}
func (m *ValidNestedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidNestedRequest.Marshal(b, m, deterministic)
}
func (dst *ValidNestedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidNestedRequest.Merge(dst, src)
}
func (m *ValidNestedRequest) XXX_Size() int {
	return xxx_messageInfo_ValidNestedRequest.Size(m)
}
func (m *ValidNestedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidNestedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidNestedRequest proto.InternalMessageInfo

func (m *ValidNestedRequest) GetInnerMessage() *ValidRequest {
	if m != nil {
		return m.InnerMessage
	}
	return nil
}

type ValidNestedSharedRequest struct {
	NestedTargetRepo     *gitalypb.ObjectPool `protobuf:"bytes,1,opt,name=nested_target_repo,json=nestedTargetRepo,proto3" json:"nested_target_repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ValidNestedSharedRequest) Reset()         { *m = ValidNestedSharedRequest{} }
func (m *ValidNestedSharedRequest) String() string { return proto.CompactTextString(m) }
func (*ValidNestedSharedRequest) ProtoMessage()    {}
func (*ValidNestedSharedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_valid_28fe26eda283975a, []int{3}
}
func (m *ValidNestedSharedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidNestedSharedRequest.Unmarshal(m, b)
}
func (m *ValidNestedSharedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidNestedSharedRequest.Marshal(b, m, deterministic)
}
func (dst *ValidNestedSharedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidNestedSharedRequest.Merge(dst, src)
}
func (m *ValidNestedSharedRequest) XXX_Size() int {
	return xxx_messageInfo_ValidNestedSharedRequest.Size(m)
}
func (m *ValidNestedSharedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidNestedSharedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidNestedSharedRequest proto.InternalMessageInfo

func (m *ValidNestedSharedRequest) GetNestedTargetRepo() *gitalypb.ObjectPool {
	if m != nil {
		return m.NestedTargetRepo
	}
	return nil
}

type ValidInnerNestedRequest struct {
	Header               *ValidInnerNestedRequest_Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ValidInnerNestedRequest) Reset()         { *m = ValidInnerNestedRequest{} }
func (m *ValidInnerNestedRequest) String() string { return proto.CompactTextString(m) }
func (*ValidInnerNestedRequest) ProtoMessage()    {}
func (*ValidInnerNestedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_valid_28fe26eda283975a, []int{4}
}
func (m *ValidInnerNestedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidInnerNestedRequest.Unmarshal(m, b)
}
func (m *ValidInnerNestedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidInnerNestedRequest.Marshal(b, m, deterministic)
}
func (dst *ValidInnerNestedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidInnerNestedRequest.Merge(dst, src)
}
func (m *ValidInnerNestedRequest) XXX_Size() int {
	return xxx_messageInfo_ValidInnerNestedRequest.Size(m)
}
func (m *ValidInnerNestedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidInnerNestedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidInnerNestedRequest proto.InternalMessageInfo

func (m *ValidInnerNestedRequest) GetHeader() *ValidInnerNestedRequest_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

type ValidInnerNestedRequest_Header struct {
	Destination          *gitalypb.Repository `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ValidInnerNestedRequest_Header) Reset()         { *m = ValidInnerNestedRequest_Header{} }
func (m *ValidInnerNestedRequest_Header) String() string { return proto.CompactTextString(m) }
func (*ValidInnerNestedRequest_Header) ProtoMessage()    {}
func (*ValidInnerNestedRequest_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_valid_28fe26eda283975a, []int{4, 0}
}
func (m *ValidInnerNestedRequest_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidInnerNestedRequest_Header.Unmarshal(m, b)
}
func (m *ValidInnerNestedRequest_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidInnerNestedRequest_Header.Marshal(b, m, deterministic)
}
func (dst *ValidInnerNestedRequest_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidInnerNestedRequest_Header.Merge(dst, src)
}
func (m *ValidInnerNestedRequest_Header) XXX_Size() int {
	return xxx_messageInfo_ValidInnerNestedRequest_Header.Size(m)
}
func (m *ValidInnerNestedRequest_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidInnerNestedRequest_Header.DiscardUnknown(m)
}

var xxx_messageInfo_ValidInnerNestedRequest_Header proto.InternalMessageInfo

func (m *ValidInnerNestedRequest_Header) GetDestination() *gitalypb.Repository {
	if m != nil {
		return m.Destination
	}
	return nil
}

func init() {
	proto.RegisterType((*ValidRequest)(nil), "test.ValidRequest")
	proto.RegisterType((*ValidResponse)(nil), "test.ValidResponse")
	proto.RegisterType((*ValidNestedRequest)(nil), "test.ValidNestedRequest")
	proto.RegisterType((*ValidNestedSharedRequest)(nil), "test.ValidNestedSharedRequest")
	proto.RegisterType((*ValidInnerNestedRequest)(nil), "test.ValidInnerNestedRequest")
	proto.RegisterType((*ValidInnerNestedRequest_Header)(nil), "test.ValidInnerNestedRequest.Header")
}

func init() {
	proto.RegisterFile("go/internal/linter/testdata/valid.proto", fileDescriptor_valid_28fe26eda283975a)
}

var fileDescriptor_valid_28fe26eda283975a = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd3, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0x07, 0x70, 0x66, 0xad, 0x35, 0x4e, 0xba, 0xb8, 0x8c, 0x07, 0x4b, 0x40, 0x91, 0x20, 0x98,
	0x53, 0x42, 0xbb, 0xab, 0xeb, 0x41, 0xa4, 0x82, 0x07, 0xf7, 0xd0, 0x5d, 0xc9, 0x2e, 0x9e, 0x84,
	0x32, 0x6d, 0x1e, 0xe9, 0x48, 0x9c, 0x89, 0x33, 0xcf, 0x42, 0x3f, 0x49, 0xbe, 0x91, 0x1f, 0xaa,
	0x27, 0xc9, 0x34, 0xd6, 0x89, 0x2d, 0x4b, 0xdb, 0x5b, 0x78, 0xfc, 0xf3, 0xcb, 0x9b, 0xf7, 0x26,
	0xf4, 0x75, 0xae, 0x12, 0x21, 0x11, 0xb4, 0xe4, 0x45, 0x52, 0xd8, 0xa7, 0x04, 0xc1, 0x60, 0xc6,
	0x91, 0x27, 0x0b, 0x5e, 0x88, 0x2c, 0x2e, 0xb5, 0x42, 0xc5, 0x3a, 0x75, 0x35, 0xe8, 0x99, 0x39,
	0xd7, 0xd0, 0xd4, 0xc2, 0x4f, 0xb4, 0xf7, 0xb5, 0x8e, 0xa4, 0xf0, 0xf3, 0x17, 0x18, 0x64, 0x17,
	0xd4, 0xcf, 0xc0, 0xa0, 0x90, 0x1c, 0x85, 0x92, 0x7d, 0xf2, 0x92, 0x44, 0xfe, 0x90, 0xc5, 0xb9,
	0x40, 0x5e, 0x2c, 0xe3, 0x14, 0x4a, 0x65, 0x04, 0x2a, 0xbd, 0x4c, 0xdd, 0x58, 0xf8, 0x84, 0x9e,
	0x36, 0x8a, 0x29, 0x95, 0x34, 0x10, 0x8e, 0x29, 0xb3, 0x85, 0x6b, 0x30, 0x08, 0x1b, 0xfc, 0x92,
	0x9e, 0x0a, 0x29, 0x41, 0x4f, 0x7e, 0x80, 0x31, 0x3c, 0x87, 0x0d, 0x5f, 0x37, 0x16, 0xbb, 0x7d,
	0xa4, 0x3d, 0x1b, 0x1c, 0xaf, 0x73, 0xe1, 0x37, 0xda, 0x77, 0xb8, 0x5b, 0x7b, 0x80, 0xbf, 0xe8,
	0x88, 0x32, 0x69, 0xcb, 0x13, 0xe4, 0x3a, 0x07, 0x9c, 0x68, 0x28, 0xd5, 0xff, 0x8d, 0xdf, 0x4c,
	0xbf, 0xc3, 0x0c, 0xbf, 0x28, 0x55, 0xa4, 0x67, 0xeb, 0xf4, 0x9d, 0x0d, 0xd7, 0x07, 0x0a, 0x2b,
	0x42, 0x9f, 0x59, 0xfe, 0xaa, 0xfe, 0x66, 0xbb, 0xe5, 0xf7, 0xb4, 0x3b, 0x07, 0x9e, 0x81, 0x6e,
	0xc4, 0x57, 0x4e, 0xaf, 0xdb, 0xf1, 0xf8, 0xb3, 0xcd, 0xa6, 0xcd, 0x3b, 0xc1, 0x07, 0xda, 0x5d,
	0x57, 0x8e, 0x9b, 0xeb, 0xf0, 0x77, 0xa7, 0x59, 0xcf, 0x2d, 0xe8, 0x85, 0x98, 0x01, 0x1b, 0x51,
	0x7a, 0x07, 0x06, 0xc7, 0x80, 0x73, 0x95, 0xb1, 0x1d, 0x83, 0x0b, 0x9e, 0xb6, 0x6a, 0xcd, 0x3a,
	0x1e, 0xaf, 0xaa, 0xe8, 0xa1, 0x77, 0x12, 0x90, 0x01, 0xfb, 0x48, 0xfd, 0x7f, 0xc2, 0xf0, 0x50,
	0x82, 0x6c, 0x11, 0xe7, 0x47, 0x11, 0x23, 0x97, 0xb8, 0xd8, 0x9f, 0xf0, 0x56, 0x55, 0xd4, 0xf1,
	0xc8, 0x19, 0x61, 0x57, 0xae, 0xf0, 0x86, 0xf5, 0x9d, 0x74, 0x6b, 0x25, 0xbb, 0x1d, 0x7f, 0x55,
	0x45, 0x8f, 0x3c, 0x12, 0x3c, 0x18, 0xc4, 0x03, 0x76, 0xe3, 0x52, 0x6f, 0xd9, 0x8b, 0x2d, 0xaa,
	0x75, 0xe1, 0xf6, 0x00, 0xaf, 0x5d, 0xf0, 0x92, 0x3d, 0xbf, 0xf7, 0xce, 0xec, 0xe1, 0xb5, 0xa6,
	0xf5, 0xee, 0xf0, 0x69, 0x9d, 0x4c, 0xbb, 0xf6, 0x6f, 0x3f, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x0e, 0x93, 0x1a, 0xd9, 0x2c, 0x04, 0x00, 0x00,
}
