#!/usr/bin/env ruby

# Tests inputs to pre-receive

abort("FAIL") if $stdin.read.empty?
abort("FAIL") if %w[GL_ID GL_REPOSITORY GL_PROTOCOL GL_USERNAME].any? { |k| ENV[k].nil? || ENV[k].empty? }

puts "OK"

