require 'json'

VENDOR_JSON = 'vendor/vendor.json'

if git.modified_files.include?(VENDOR_JSON)
  parsed_json = JSON.parse(File.read(VENDOR_JSON))

  proto = parsed_json["package"]&.find { |h| h["path"].start_with?("gitlab.com/gitlab-org/gitaly-proto") }

  unless proto["version"] && proto["version"] =~ /\Av\d+\./
    fail("gitaly-proto version is incorrect")
  end
end

# vim: ft=ruby
