# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: blob.proto for package 'gitaly'

require 'grpc'
require 'blob_pb'

module Gitaly
  module BlobService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gitaly.BlobService'

      # GetBlob returns the contents of a blob object referenced by its object
      # ID. We use a stream to return a chunked arbitrarily large binary
      # response
      rpc :GetBlob, GetBlobRequest, stream(GetBlobResponse)
      rpc :GetBlobs, GetBlobsRequest, stream(GetBlobsResponse)
      rpc :GetLFSPointers, GetLFSPointersRequest, stream(GetLFSPointersResponse)
      rpc :GetNewLFSPointers, GetNewLFSPointersRequest, stream(GetNewLFSPointersResponse)
      rpc :GetAllLFSPointers, GetAllLFSPointersRequest, stream(GetAllLFSPointersResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
