# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: praefect.proto

require 'google/protobuf'

require 'shared_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gitaly.ListRepositoriesRequest" do
  end
  add_message "gitaly.ListRepositoriesResponse" do
    optional :primary, :message, 1, "gitaly.ListRepositoriesResponse.RepositoryDetails"
    repeated :replicas, :message, 2, "gitaly.ListRepositoriesResponse.RepositoryDetails"
  end
  add_message "gitaly.ListRepositoriesResponse.RepositoryDetails" do
    optional :repository, :message, 1, "gitaly.Repository"
    optional :checksum, :string, 2
  end
end

module Gitaly
  ListRepositoriesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ListRepositoriesRequest").msgclass
  ListRepositoriesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ListRepositoriesResponse").msgclass
  ListRepositoriesResponse::RepositoryDetails = Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ListRepositoriesResponse.RepositoryDetails").msgclass
end
