# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: praefect.proto for package 'gitaly'

require 'grpc'
require 'praefect_pb'

module Gitaly
  module PraefectInfoService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gitaly.PraefectInfoService'

      rpc :RepositoryReplicas, RepositoryReplicasRequest, RepositoryReplicasResponse
      # ConsistencyCheck will perform a consistency check on the requested
      # virtual storage backend. A stream of repository statuses will be sent
      # back indicating which repos are consistent with the primary and which ones
      # need repair.
      rpc :ConsistencyCheck, ConsistencyCheckRequest, stream(ConsistencyCheckResponse)
      # DatalossCheck returns the count of dead replica jobs created within a given
      # timeframe. Dead replica jobs can indicate data loss and can be helpful in debugging
      # impact of a primary node failure.
      rpc :DatalossCheck, DatalossCheckRequest, DatalossCheckResponse
    end

    Stub = Service.rpc_stub_class
  end
end
