// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conflicts.proto

package gitalypb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListConflictFilesRequest struct {
	Repository           *Repository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	OurCommitOid         string      `protobuf:"bytes,2,opt,name=our_commit_oid,json=ourCommitOid,proto3" json:"our_commit_oid,omitempty"`
	TheirCommitOid       string      `protobuf:"bytes,3,opt,name=their_commit_oid,json=theirCommitOid,proto3" json:"their_commit_oid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListConflictFilesRequest) Reset()         { *m = ListConflictFilesRequest{} }
func (m *ListConflictFilesRequest) String() string { return proto.CompactTextString(m) }
func (*ListConflictFilesRequest) ProtoMessage()    {}
func (*ListConflictFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fc8937e7d75862, []int{0}
}

func (m *ListConflictFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListConflictFilesRequest.Unmarshal(m, b)
}
func (m *ListConflictFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListConflictFilesRequest.Marshal(b, m, deterministic)
}
func (m *ListConflictFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListConflictFilesRequest.Merge(m, src)
}
func (m *ListConflictFilesRequest) XXX_Size() int {
	return xxx_messageInfo_ListConflictFilesRequest.Size(m)
}
func (m *ListConflictFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListConflictFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListConflictFilesRequest proto.InternalMessageInfo

func (m *ListConflictFilesRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *ListConflictFilesRequest) GetOurCommitOid() string {
	if m != nil {
		return m.OurCommitOid
	}
	return ""
}

func (m *ListConflictFilesRequest) GetTheirCommitOid() string {
	if m != nil {
		return m.TheirCommitOid
	}
	return ""
}

type ConflictFileHeader struct {
	CommitOid            string   `protobuf:"bytes,2,opt,name=commit_oid,json=commitOid,proto3" json:"commit_oid,omitempty"`
	TheirPath            []byte   `protobuf:"bytes,3,opt,name=their_path,json=theirPath,proto3" json:"their_path,omitempty"`
	OurPath              []byte   `protobuf:"bytes,4,opt,name=our_path,json=ourPath,proto3" json:"our_path,omitempty"`
	OurMode              int32    `protobuf:"varint,5,opt,name=our_mode,json=ourMode,proto3" json:"our_mode,omitempty"`
	AncestorPath         []byte   `protobuf:"bytes,6,opt,name=ancestor_path,json=ancestorPath,proto3" json:"ancestor_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConflictFileHeader) Reset()         { *m = ConflictFileHeader{} }
func (m *ConflictFileHeader) String() string { return proto.CompactTextString(m) }
func (*ConflictFileHeader) ProtoMessage()    {}
func (*ConflictFileHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fc8937e7d75862, []int{1}
}

func (m *ConflictFileHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConflictFileHeader.Unmarshal(m, b)
}
func (m *ConflictFileHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConflictFileHeader.Marshal(b, m, deterministic)
}
func (m *ConflictFileHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConflictFileHeader.Merge(m, src)
}
func (m *ConflictFileHeader) XXX_Size() int {
	return xxx_messageInfo_ConflictFileHeader.Size(m)
}
func (m *ConflictFileHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ConflictFileHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ConflictFileHeader proto.InternalMessageInfo

func (m *ConflictFileHeader) GetCommitOid() string {
	if m != nil {
		return m.CommitOid
	}
	return ""
}

func (m *ConflictFileHeader) GetTheirPath() []byte {
	if m != nil {
		return m.TheirPath
	}
	return nil
}

func (m *ConflictFileHeader) GetOurPath() []byte {
	if m != nil {
		return m.OurPath
	}
	return nil
}

func (m *ConflictFileHeader) GetOurMode() int32 {
	if m != nil {
		return m.OurMode
	}
	return 0
}

func (m *ConflictFileHeader) GetAncestorPath() []byte {
	if m != nil {
		return m.AncestorPath
	}
	return nil
}

type ConflictFile struct {
	// Types that are valid to be assigned to ConflictFilePayload:
	//	*ConflictFile_Header
	//	*ConflictFile_Content
	ConflictFilePayload  isConflictFile_ConflictFilePayload `protobuf_oneof:"conflict_file_payload"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ConflictFile) Reset()         { *m = ConflictFile{} }
func (m *ConflictFile) String() string { return proto.CompactTextString(m) }
func (*ConflictFile) ProtoMessage()    {}
func (*ConflictFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fc8937e7d75862, []int{2}
}

func (m *ConflictFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConflictFile.Unmarshal(m, b)
}
func (m *ConflictFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConflictFile.Marshal(b, m, deterministic)
}
func (m *ConflictFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConflictFile.Merge(m, src)
}
func (m *ConflictFile) XXX_Size() int {
	return xxx_messageInfo_ConflictFile.Size(m)
}
func (m *ConflictFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ConflictFile.DiscardUnknown(m)
}

var xxx_messageInfo_ConflictFile proto.InternalMessageInfo

type isConflictFile_ConflictFilePayload interface {
	isConflictFile_ConflictFilePayload()
}

type ConflictFile_Header struct {
	Header *ConflictFileHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type ConflictFile_Content struct {
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3,oneof"`
}

func (*ConflictFile_Header) isConflictFile_ConflictFilePayload() {}

func (*ConflictFile_Content) isConflictFile_ConflictFilePayload() {}

func (m *ConflictFile) GetConflictFilePayload() isConflictFile_ConflictFilePayload {
	if m != nil {
		return m.ConflictFilePayload
	}
	return nil
}

func (m *ConflictFile) GetHeader() *ConflictFileHeader {
	if x, ok := m.GetConflictFilePayload().(*ConflictFile_Header); ok {
		return x.Header
	}
	return nil
}

func (m *ConflictFile) GetContent() []byte {
	if x, ok := m.GetConflictFilePayload().(*ConflictFile_Content); ok {
		return x.Content
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ConflictFile) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ConflictFile_Header)(nil),
		(*ConflictFile_Content)(nil),
	}
}

type ListConflictFilesResponse struct {
	Files                []*ConflictFile `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListConflictFilesResponse) Reset()         { *m = ListConflictFilesResponse{} }
func (m *ListConflictFilesResponse) String() string { return proto.CompactTextString(m) }
func (*ListConflictFilesResponse) ProtoMessage()    {}
func (*ListConflictFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fc8937e7d75862, []int{3}
}

func (m *ListConflictFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListConflictFilesResponse.Unmarshal(m, b)
}
func (m *ListConflictFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListConflictFilesResponse.Marshal(b, m, deterministic)
}
func (m *ListConflictFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListConflictFilesResponse.Merge(m, src)
}
func (m *ListConflictFilesResponse) XXX_Size() int {
	return xxx_messageInfo_ListConflictFilesResponse.Size(m)
}
func (m *ListConflictFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListConflictFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListConflictFilesResponse proto.InternalMessageInfo

func (m *ListConflictFilesResponse) GetFiles() []*ConflictFile {
	if m != nil {
		return m.Files
	}
	return nil
}

type ResolveConflictsRequestHeader struct {
	Repository           *Repository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	OurCommitOid         string      `protobuf:"bytes,2,opt,name=our_commit_oid,json=ourCommitOid,proto3" json:"our_commit_oid,omitempty"`
	TargetRepository     *Repository `protobuf:"bytes,3,opt,name=target_repository,json=targetRepository,proto3" json:"target_repository,omitempty"`
	TheirCommitOid       string      `protobuf:"bytes,4,opt,name=their_commit_oid,json=theirCommitOid,proto3" json:"their_commit_oid,omitempty"`
	SourceBranch         []byte      `protobuf:"bytes,5,opt,name=source_branch,json=sourceBranch,proto3" json:"source_branch,omitempty"`
	TargetBranch         []byte      `protobuf:"bytes,6,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`
	CommitMessage        []byte      `protobuf:"bytes,7,opt,name=commit_message,json=commitMessage,proto3" json:"commit_message,omitempty"`
	User                 *User       `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResolveConflictsRequestHeader) Reset()         { *m = ResolveConflictsRequestHeader{} }
func (m *ResolveConflictsRequestHeader) String() string { return proto.CompactTextString(m) }
func (*ResolveConflictsRequestHeader) ProtoMessage()    {}
func (*ResolveConflictsRequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fc8937e7d75862, []int{4}
}

func (m *ResolveConflictsRequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveConflictsRequestHeader.Unmarshal(m, b)
}
func (m *ResolveConflictsRequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveConflictsRequestHeader.Marshal(b, m, deterministic)
}
func (m *ResolveConflictsRequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveConflictsRequestHeader.Merge(m, src)
}
func (m *ResolveConflictsRequestHeader) XXX_Size() int {
	return xxx_messageInfo_ResolveConflictsRequestHeader.Size(m)
}
func (m *ResolveConflictsRequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveConflictsRequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveConflictsRequestHeader proto.InternalMessageInfo

func (m *ResolveConflictsRequestHeader) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *ResolveConflictsRequestHeader) GetOurCommitOid() string {
	if m != nil {
		return m.OurCommitOid
	}
	return ""
}

func (m *ResolveConflictsRequestHeader) GetTargetRepository() *Repository {
	if m != nil {
		return m.TargetRepository
	}
	return nil
}

func (m *ResolveConflictsRequestHeader) GetTheirCommitOid() string {
	if m != nil {
		return m.TheirCommitOid
	}
	return ""
}

func (m *ResolveConflictsRequestHeader) GetSourceBranch() []byte {
	if m != nil {
		return m.SourceBranch
	}
	return nil
}

func (m *ResolveConflictsRequestHeader) GetTargetBranch() []byte {
	if m != nil {
		return m.TargetBranch
	}
	return nil
}

func (m *ResolveConflictsRequestHeader) GetCommitMessage() []byte {
	if m != nil {
		return m.CommitMessage
	}
	return nil
}

func (m *ResolveConflictsRequestHeader) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ResolveConflictsRequest struct {
	// Types that are valid to be assigned to ResolveConflictsRequestPayload:
	//	*ResolveConflictsRequest_Header
	//	*ResolveConflictsRequest_FilesJson
	ResolveConflictsRequestPayload isResolveConflictsRequest_ResolveConflictsRequestPayload `protobuf_oneof:"resolve_conflicts_request_payload"`
	XXX_NoUnkeyedLiteral           struct{}                                                 `json:"-"`
	XXX_unrecognized               []byte                                                   `json:"-"`
	XXX_sizecache                  int32                                                    `json:"-"`
}

func (m *ResolveConflictsRequest) Reset()         { *m = ResolveConflictsRequest{} }
func (m *ResolveConflictsRequest) String() string { return proto.CompactTextString(m) }
func (*ResolveConflictsRequest) ProtoMessage()    {}
func (*ResolveConflictsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fc8937e7d75862, []int{5}
}

func (m *ResolveConflictsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveConflictsRequest.Unmarshal(m, b)
}
func (m *ResolveConflictsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveConflictsRequest.Marshal(b, m, deterministic)
}
func (m *ResolveConflictsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveConflictsRequest.Merge(m, src)
}
func (m *ResolveConflictsRequest) XXX_Size() int {
	return xxx_messageInfo_ResolveConflictsRequest.Size(m)
}
func (m *ResolveConflictsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveConflictsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveConflictsRequest proto.InternalMessageInfo

type isResolveConflictsRequest_ResolveConflictsRequestPayload interface {
	isResolveConflictsRequest_ResolveConflictsRequestPayload()
}

type ResolveConflictsRequest_Header struct {
	Header *ResolveConflictsRequestHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type ResolveConflictsRequest_FilesJson struct {
	FilesJson []byte `protobuf:"bytes,2,opt,name=files_json,json=filesJson,proto3,oneof"`
}

func (*ResolveConflictsRequest_Header) isResolveConflictsRequest_ResolveConflictsRequestPayload() {}

func (*ResolveConflictsRequest_FilesJson) isResolveConflictsRequest_ResolveConflictsRequestPayload() {
}

func (m *ResolveConflictsRequest) GetResolveConflictsRequestPayload() isResolveConflictsRequest_ResolveConflictsRequestPayload {
	if m != nil {
		return m.ResolveConflictsRequestPayload
	}
	return nil
}

func (m *ResolveConflictsRequest) GetHeader() *ResolveConflictsRequestHeader {
	if x, ok := m.GetResolveConflictsRequestPayload().(*ResolveConflictsRequest_Header); ok {
		return x.Header
	}
	return nil
}

func (m *ResolveConflictsRequest) GetFilesJson() []byte {
	if x, ok := m.GetResolveConflictsRequestPayload().(*ResolveConflictsRequest_FilesJson); ok {
		return x.FilesJson
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ResolveConflictsRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ResolveConflictsRequest_Header)(nil),
		(*ResolveConflictsRequest_FilesJson)(nil),
	}
}

type ResolveConflictsResponse struct {
	ResolutionError      string   `protobuf:"bytes,1,opt,name=resolution_error,json=resolutionError,proto3" json:"resolution_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolveConflictsResponse) Reset()         { *m = ResolveConflictsResponse{} }
func (m *ResolveConflictsResponse) String() string { return proto.CompactTextString(m) }
func (*ResolveConflictsResponse) ProtoMessage()    {}
func (*ResolveConflictsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fc8937e7d75862, []int{6}
}

func (m *ResolveConflictsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveConflictsResponse.Unmarshal(m, b)
}
func (m *ResolveConflictsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveConflictsResponse.Marshal(b, m, deterministic)
}
func (m *ResolveConflictsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveConflictsResponse.Merge(m, src)
}
func (m *ResolveConflictsResponse) XXX_Size() int {
	return xxx_messageInfo_ResolveConflictsResponse.Size(m)
}
func (m *ResolveConflictsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveConflictsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveConflictsResponse proto.InternalMessageInfo

func (m *ResolveConflictsResponse) GetResolutionError() string {
	if m != nil {
		return m.ResolutionError
	}
	return ""
}

func init() {
	proto.RegisterType((*ListConflictFilesRequest)(nil), "gitaly.ListConflictFilesRequest")
	proto.RegisterType((*ConflictFileHeader)(nil), "gitaly.ConflictFileHeader")
	proto.RegisterType((*ConflictFile)(nil), "gitaly.ConflictFile")
	proto.RegisterType((*ListConflictFilesResponse)(nil), "gitaly.ListConflictFilesResponse")
	proto.RegisterType((*ResolveConflictsRequestHeader)(nil), "gitaly.ResolveConflictsRequestHeader")
	proto.RegisterType((*ResolveConflictsRequest)(nil), "gitaly.ResolveConflictsRequest")
	proto.RegisterType((*ResolveConflictsResponse)(nil), "gitaly.ResolveConflictsResponse")
}

func init() { proto.RegisterFile("conflicts.proto", fileDescriptor_28fc8937e7d75862) }

var fileDescriptor_28fc8937e7d75862 = []byte{
	// 646 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x9d, 0xbb, 0xae, 0x6b, 0xef, 0xb2, 0xad, 0xb3, 0x40, 0xcb, 0x2a, 0x4d, 0xcb, 0x32, 0x26,
	0x05, 0x04, 0xed, 0x34, 0x78, 0xe0, 0x6d, 0x52, 0xa7, 0xc1, 0x34, 0x31, 0x81, 0x8c, 0x78, 0xe1,
	0x25, 0x4a, 0x13, 0xaf, 0x35, 0x4a, 0xe3, 0x60, 0x3b, 0x93, 0xfa, 0x25, 0xf0, 0xc8, 0x03, 0x7f,
	0xc0, 0x3f, 0xf0, 0x0b, 0xfc, 0x0b, 0x12, 0x12, 0x8a, 0x9d, 0x64, 0xdd, 0xda, 0x8e, 0x27, 0xde,
	0x92, 0x73, 0x8f, 0xcf, 0x3d, 0xbe, 0xf7, 0xc8, 0xb0, 0x19, 0xf2, 0xe4, 0x2a, 0x66, 0xa1, 0x92,
	0xdd, 0x54, 0x70, 0xc5, 0x71, 0x63, 0xc8, 0x54, 0x10, 0x4f, 0x3a, 0x10, 0xb3, 0x44, 0x19, 0xac,
	0x63, 0xc9, 0x51, 0x20, 0x68, 0x64, 0xfe, 0xdc, 0xef, 0x08, 0xec, 0x37, 0x4c, 0xaa, 0xd3, 0xe2,
	0xe4, 0x2b, 0x16, 0x53, 0x49, 0xe8, 0xe7, 0x8c, 0x4a, 0x85, 0x5f, 0x02, 0x08, 0x9a, 0x72, 0xc9,
	0x14, 0x17, 0x13, 0x1b, 0x39, 0xc8, 0x5b, 0x3b, 0xc6, 0x5d, 0xa3, 0xd9, 0x25, 0x55, 0xa5, 0x5f,
	0xff, 0xfa, 0xf3, 0x29, 0x22, 0x53, 0x5c, 0xfc, 0x08, 0x36, 0x78, 0x26, 0xfc, 0x90, 0x8f, 0xc7,
	0x4c, 0xf9, 0x9c, 0x45, 0x76, 0xcd, 0x41, 0x5e, 0x8b, 0x58, 0x3c, 0x13, 0xa7, 0x1a, 0x7c, 0xcb,
	0x22, 0xec, 0x41, 0x5b, 0x8d, 0x28, 0xbb, 0xc5, 0x5b, 0xd6, 0xbc, 0x0d, 0x8d, 0x57, 0x4c, 0xf7,
	0x07, 0x02, 0x3c, 0x6d, 0xf1, 0x9c, 0x06, 0x11, 0x15, 0x78, 0x17, 0x60, 0xa6, 0x45, 0x2b, 0xac,
	0xf4, 0x77, 0x01, 0x8c, 0x7e, 0x1a, 0xa8, 0x91, 0x56, 0xb6, 0x48, 0x4b, 0x23, 0xef, 0x02, 0x35,
	0xc2, 0x3b, 0xd0, 0xcc, 0x4d, 0xea, 0x62, 0x5d, 0x17, 0x57, 0x79, 0x76, 0xab, 0x34, 0xe6, 0x11,
	0xb5, 0x57, 0x1c, 0xe4, 0xad, 0xe8, 0xd2, 0x25, 0x8f, 0x28, 0x3e, 0x80, 0xf5, 0x20, 0x09, 0xa9,
	0x54, 0xbc, 0x38, 0xda, 0xd0, 0x47, 0xad, 0x12, 0xcc, 0xcf, 0x5f, 0xd4, 0x9b, 0xa8, 0x5d, 0x73,
	0x27, 0x60, 0x4d, 0x9b, 0xc6, 0x2f, 0xa0, 0x31, 0xd2, 0xc6, 0x8b, 0x59, 0x76, 0xca, 0x59, 0xce,
	0x5e, 0xed, 0x7c, 0x89, 0x14, 0x5c, 0xdc, 0x81, 0xd5, 0x90, 0x27, 0x8a, 0x26, 0x4a, 0xdf, 0xd0,
	0x3a, 0x5f, 0x22, 0x25, 0xd0, 0xdf, 0x86, 0x87, 0xe5, 0xce, 0xfd, 0x2b, 0x16, 0x53, 0x3f, 0x0d,
	0x26, 0x31, 0x0f, 0x22, 0xf7, 0x35, 0xec, 0xcc, 0x59, 0xab, 0x4c, 0x79, 0x22, 0x29, 0x7e, 0x02,
	0x2b, 0x39, 0x59, 0xda, 0xc8, 0x59, 0xf6, 0xd6, 0x8e, 0x1f, 0xcc, 0xb3, 0x41, 0x0c, 0xc5, 0xfd,
	0x53, 0x83, 0x5d, 0x42, 0x25, 0x8f, 0xaf, 0x69, 0x59, 0x2e, 0xf3, 0x51, 0x2c, 0xe1, 0x7f, 0xa7,
	0xe4, 0x04, 0xb6, 0x54, 0x20, 0x86, 0x54, 0xf9, 0x53, 0x6d, 0x96, 0x17, 0xb5, 0x21, 0x6d, 0x43,
	0xbe, 0x41, 0xe6, 0xc6, 0xac, 0x3e, 0x2f, 0x66, 0xf9, 0x6e, 0x25, 0xcf, 0x44, 0x48, 0xfd, 0x81,
	0x08, 0x92, 0x70, 0xa4, 0x77, 0x6f, 0x11, 0xcb, 0x80, 0x7d, 0x8d, 0xe5, 0xa4, 0xc2, 0x4f, 0x41,
	0x2a, 0x02, 0x60, 0xc0, 0x82, 0x74, 0x08, 0x1b, 0x45, 0xb7, 0x31, 0x95, 0x32, 0x18, 0x52, 0x7b,
	0x55, 0xb3, 0xd6, 0x0d, 0x7a, 0x69, 0x40, 0xec, 0x40, 0x3d, 0x93, 0x54, 0xd8, 0x4d, 0x7d, 0x1d,
	0xab, 0xbc, 0xce, 0x07, 0x49, 0x05, 0xd1, 0x15, 0xf7, 0x1b, 0x82, 0xed, 0x05, 0xf3, 0xc7, 0x27,
	0x77, 0xf2, 0x74, 0x78, 0x33, 0x8e, 0x7b, 0x16, 0x36, 0x15, 0xad, 0x3d, 0x00, 0xbd, 0x65, 0xff,
	0x93, 0xe4, 0x49, 0x95, 0xae, 0x96, 0xc6, 0x2e, 0x24, 0x4f, 0xfa, 0x07, 0xb0, 0x2f, 0x8c, 0x96,
	0x5f, 0xbd, 0x2d, 0xbe, 0x30, 0x6a, 0x55, 0xd6, 0xce, 0xc0, 0x9e, 0x6d, 0x58, 0x44, 0xed, 0x31,
	0xb4, 0xb5, 0x40, 0xa6, 0x18, 0x4f, 0x7c, 0x2a, 0x04, 0x37, 0x66, 0x5b, 0x64, 0xf3, 0x06, 0x3f,
	0xcb, 0xe1, 0xe3, 0x5f, 0x08, 0xda, 0x95, 0xc0, 0x7b, 0x2a, 0xae, 0x59, 0x48, 0xf1, 0x00, 0xb6,
	0x66, 0x72, 0x8c, 0x9d, 0xf2, 0x9e, 0x8b, 0x5e, 0xae, 0xce, 0xfe, 0x3d, 0x0c, 0xe3, 0xcc, 0x6d,
	0xfc, 0xfe, 0xe2, 0xd5, 0x9a, 0xb5, 0x23, 0x84, 0x7d, 0x68, 0xdf, 0xf5, 0x8f, 0xf7, 0xfe, 0x31,
	0xca, 0x8e, 0xb3, 0x98, 0x70, 0xab, 0x01, 0xf2, 0x50, 0xff, 0xe8, 0x63, 0x4e, 0x8e, 0x83, 0x41,
	0x37, 0xe4, 0xe3, 0x9e, 0xf9, 0x7c, 0xc6, 0xc5, 0xb0, 0x67, 0x24, 0x7a, 0xfa, 0x29, 0xee, 0x0d,
	0x79, 0xf1, 0x9f, 0x0e, 0x06, 0x0d, 0x0d, 0x3d, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x80, 0x8f,
	0x22, 0x49, 0xd2, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConflictsServiceClient is the client API for ConflictsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConflictsServiceClient interface {
	ListConflictFiles(ctx context.Context, in *ListConflictFilesRequest, opts ...grpc.CallOption) (ConflictsService_ListConflictFilesClient, error)
	ResolveConflicts(ctx context.Context, opts ...grpc.CallOption) (ConflictsService_ResolveConflictsClient, error)
}

type conflictsServiceClient struct {
	cc *grpc.ClientConn
}

func NewConflictsServiceClient(cc *grpc.ClientConn) ConflictsServiceClient {
	return &conflictsServiceClient{cc}
}

func (c *conflictsServiceClient) ListConflictFiles(ctx context.Context, in *ListConflictFilesRequest, opts ...grpc.CallOption) (ConflictsService_ListConflictFilesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConflictsService_serviceDesc.Streams[0], "/gitaly.ConflictsService/ListConflictFiles", opts...)
	if err != nil {
		return nil, err
	}
	x := &conflictsServiceListConflictFilesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConflictsService_ListConflictFilesClient interface {
	Recv() (*ListConflictFilesResponse, error)
	grpc.ClientStream
}

type conflictsServiceListConflictFilesClient struct {
	grpc.ClientStream
}

func (x *conflictsServiceListConflictFilesClient) Recv() (*ListConflictFilesResponse, error) {
	m := new(ListConflictFilesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *conflictsServiceClient) ResolveConflicts(ctx context.Context, opts ...grpc.CallOption) (ConflictsService_ResolveConflictsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConflictsService_serviceDesc.Streams[1], "/gitaly.ConflictsService/ResolveConflicts", opts...)
	if err != nil {
		return nil, err
	}
	x := &conflictsServiceResolveConflictsClient{stream}
	return x, nil
}

type ConflictsService_ResolveConflictsClient interface {
	Send(*ResolveConflictsRequest) error
	CloseAndRecv() (*ResolveConflictsResponse, error)
	grpc.ClientStream
}

type conflictsServiceResolveConflictsClient struct {
	grpc.ClientStream
}

func (x *conflictsServiceResolveConflictsClient) Send(m *ResolveConflictsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *conflictsServiceResolveConflictsClient) CloseAndRecv() (*ResolveConflictsResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ResolveConflictsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConflictsServiceServer is the server API for ConflictsService service.
type ConflictsServiceServer interface {
	ListConflictFiles(*ListConflictFilesRequest, ConflictsService_ListConflictFilesServer) error
	ResolveConflicts(ConflictsService_ResolveConflictsServer) error
}

// UnimplementedConflictsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConflictsServiceServer struct {
}

func (*UnimplementedConflictsServiceServer) ListConflictFiles(req *ListConflictFilesRequest, srv ConflictsService_ListConflictFilesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListConflictFiles not implemented")
}
func (*UnimplementedConflictsServiceServer) ResolveConflicts(srv ConflictsService_ResolveConflictsServer) error {
	return status.Errorf(codes.Unimplemented, "method ResolveConflicts not implemented")
}

func RegisterConflictsServiceServer(s *grpc.Server, srv ConflictsServiceServer) {
	s.RegisterService(&_ConflictsService_serviceDesc, srv)
}

func _ConflictsService_ListConflictFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListConflictFilesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConflictsServiceServer).ListConflictFiles(m, &conflictsServiceListConflictFilesServer{stream})
}

type ConflictsService_ListConflictFilesServer interface {
	Send(*ListConflictFilesResponse) error
	grpc.ServerStream
}

type conflictsServiceListConflictFilesServer struct {
	grpc.ServerStream
}

func (x *conflictsServiceListConflictFilesServer) Send(m *ListConflictFilesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ConflictsService_ResolveConflicts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConflictsServiceServer).ResolveConflicts(&conflictsServiceResolveConflictsServer{stream})
}

type ConflictsService_ResolveConflictsServer interface {
	SendAndClose(*ResolveConflictsResponse) error
	Recv() (*ResolveConflictsRequest, error)
	grpc.ServerStream
}

type conflictsServiceResolveConflictsServer struct {
	grpc.ServerStream
}

func (x *conflictsServiceResolveConflictsServer) SendAndClose(m *ResolveConflictsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *conflictsServiceResolveConflictsServer) Recv() (*ResolveConflictsRequest, error) {
	m := new(ResolveConflictsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ConflictsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gitaly.ConflictsService",
	HandlerType: (*ConflictsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListConflictFiles",
			Handler:       _ConflictsService_ListConflictFiles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ResolveConflicts",
			Handler:       _ConflictsService_ResolveConflicts_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "conflicts.proto",
}
